spring:
  application:
    name: razorpay
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/razorpay-db}
    username: ${DB_USER:pulkit}
    password: ${DB_PASS:password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    listener:
      ack-mode: manual
    bootstrap-servers: ${KAFKA_BROKERS:localhost:29092}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
#      in case of retry make sure the new events are not generated
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 3
        spring.json.add.type.headers: false

    consumer:
      group-id: razorpay-monolith
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pb7technologies.razorpay.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: java.util.LinkedHashMap

  threads:
    virtual:
      enabled: true

vault:
  master-key: HgVtmhU8x2/tZT+Xv4Ywfz1Gyxv16bLB7r9lPK7mTvI=

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: 996edcefccf29a1d80f301e6307dd1934df6d63f23f79a896438fd6a3ed936bd

app:
  rate-limit:
    method: fixed
    api-key:
      requests-per-minute: 1000

  kafka:
    topics:
      payment: payments.events
      order: orders.events
      refund: refunds.events
      settlement: settlements.events

  webhook:
    properties:
      delivery:
        redis-key: "webhook-retry"
        poll-batch-size: 100
